plugins {
    id "architectury-plugin" version "3.4-SNAPSHOT"
    id "dev.architectury.loom" version "1.9-SNAPSHOT" apply false
    id "org.jetbrains.kotlin.jvm" version "2.2.21" apply false
}

ext.hash_id = ""
def isDev = project.hasProperty("isDev") ? project.property("isDev").toBoolean() : false
if (isDev) {
    try {
        ext.hash_id = 'git rev-parse --short HEAD'.execute().text.trim()
    } catch (Exception ignored) {
        ext.hash_id = "unknown"
    }
}

version = project.mod_version + (isDev ? "-dev-${hash_id}" : "")

architectury {
    minecraft = rootProject.minecraft_version
}

subprojects {
    apply plugin: "dev.architectury.loom"
    version = rootProject.version

    loom {
        silentMojangMappingsLicense()
    }

    dependencies {
        minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
        mappings loom.officialMojangMappings()
    }
}

allprojects {
    apply plugin: "java"
    apply plugin: "architectury-plugin"
    apply plugin: "maven-publish"

    base {
        archivesName = "${rootProject.archives_base_name}-${rootProject.minecraft_version}-${project.name}"
    }

    group = rootProject.maven_group

    repositories {
        mavenCentral()
        gradlePluginPortal()
        maven { url = "https://maven.fabricmc.net/" }
        maven { url = "https://maven.architectury.dev/" }
        maven { url = "https://maven.neoforged.net/releases/" }
        maven { url = "https://maven.impactdev.net/repository/development/" }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
        options.release = 21
    }

    java {
        def targetJavaVersion = 21
        def javaVersion = JavaVersion.toVersion(targetJavaVersion)
        if (JavaVersion.current() < javaVersion) {
            toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
        }
        withSourcesJar()
    }
}
